# 路径
data_path: data/sample_data.pkl
result_path: results/

preprocess:
  nan_threshold:   0.15      # 缺失率>15% 的因子直接剔除
  winsor_pct:      0.01     # 1%–99% Winsorize
  fill_method:   ts_ffill     # ts_ffill | median_cs
  smooth_window:   20        # 对单品种时间序列做 rolling mean,<=1 表示不平滑
  min_periods: 10       # 平滑时的最小观测数
  cs_zscore:       true     # 是否做横截面 z-score 标准化

# 因子
analysis:
  top_k_plot: 15          # 画分层净值曲线的因子个数
  top_k_factor: 100     # 筛选的因子个数
  n_layer: 5            # 分层数
  ic_min_obs: 10         # 计算单日 IC 至少需要的样本数
  corr_threshold: 0.9   # 相关系数上限
  ic_threshold: 0.005          # |mean IC| 下限

# 训练窗口
train_start: 2018-01-01
train_end: 2023-12-31
test_start: 2024-01-01
test_end: 2025-12-31

# 降维
dim_reduction:               # 关闭 => method: none
  method: pca                # 降维方法
  n_components: 25           # 降到多少维

# 建模
model_name: lgb # 模型名称 [lgb | xgb | rf | gbdt]
hyper_params:
  #  n_estimators: 300
  #  learning_rate: 0.05
  #  max_depth: -1
  verbose: 0
  random_state: 42

# 回测
k_long: 0.2
k_short: 0.2
transaction_cost: 0.0003